flowchart TB
    subgraph CORE[Internet / Edge / Core]
      ISP[Internet / ISP] --> R1[R1]
      R1 --> CSW1[CSW1]
      R1 --> CSW2[CSW2]
      CSW1 <-->|Layer 3 EtherChannel\nPAgP desirable| CSW2
    end

    subgraph OA[Office A]
      DSWA1[DSW-A1]
      DSWA2[DSW-A2]
      ASWA1[ASW-A1]
      ASWA2[ASW-A2]
      ASWA3[ASW-A3]
      WLC1[WLC1]
      LWAP1[LWAP1]
      LAP1[Laptop1]
      PC1[PC1]
      PC2[PC2]
      PH1[Phone1]
      PH2[Phone2]

      DSWA1 <-->|Layer 2 EtherChannel\nPAgP desirable| DSWA2
      DSWA1 --> ASWA1
      DSWA1 --> ASWA2
      DSWA2 --> ASWA2
      DSWA2 --> ASWA3

      ASWA1 --> WLC1
      ASWA1 --> LWAP1
      LWAP1 --> LAP1
      ASWA2 --> PC1
      ASWA2 --> PC2
      ASWA2 --> PH1
      ASWA3 --> PH2
    end

    subgraph OB[Office B]
      DSWB1[DSW-B1]
      DSWB2[DSW-B2]
      ASWB1[ASW-B1]
      ASWB2[ASW-B2]
      ASWB3[ASW-B3]
      LWAP2[LWAP2]
      LAP2[Laptop2]
      PC3[PC3]
      PH3[Phone3]
      SRV1[SRV1]

      DSWB1 <-->|Layer 2 EtherChannel\nLACP active| DSWB2
      DSWB1 --> ASWB1
      DSWB1 --> ASWB2
      DSWB2 --> ASWB2
      DSWB2 --> ASWB3

      ASWB1 --> LWAP2
      LWAP2 --> LAP2
      ASWB2 --> PC3
      ASWB2 --> PH3
      ASWB3 --> SRV1
    end

    CSW1 --> DSWA1
    CSW2 --> DSWA1
    CSW1 --> DSWA2
    CSW2 --> DSWA2
    CSW1 --> DSWB1
    CSW2 --> DSWB1
    CSW1 --> DSWB2
    CSW2 --> DSWB2
